In [3]:
!pip install numpy
import numpy as np
a=np.array([1,1,1,1,1])
b=np.array([2,2,2,2,2])
np.sum(a*b)

10

In [5]:
import numpy as np
a=np.array([[0,9,19,13],[1,20,5,13],[12,11,3,4]])
b=np.array([[2,0,0,0],[1,2,2,0],[2,1,1,0],[0,0,1,1]])
np.dot(a,b)

array([[47, 37, 50, 13],
       [32, 45, 58, 13],
       [41, 25, 29,  4]])

In [6]:
a=np.array([[-1,33,4,1],[0,1,1,0]])
np.mean(a)

4.875

In [7]:
!pip install scipy


In [20]:
import scipy as sc
from scipy import linalg
a=np.array([[6,0,3],[0,-1,2],[12,3,0]])
linalg.det(a)

0.0

In [21]:
linalg.eig(a)

(array([ 9.86545993e+00+0.j,  6.66242235e-17+0.j, -4.86545993e+00+0.j]),
 array([[-0.60673536, -0.21821789, -0.23816795],
        [-0.1439001 ,  0.87287156, -0.44631244],
        [-0.7817704 ,  0.43643578,  0.86260143]]))

In [22]:
a=np.array([[1,-1,-1,0],[-1,2,-1,-1],[-1,-1,2,-1],[0,-1,-1,1]])
linalg.eig(a)

(array([-1.+0.j,  1.+0.j,  3.+0.j,  3.+0.j]),
 array([[ 5.00000000e-01,  7.07106781e-01,  5.00000000e-01,
         -8.70388280e-02],
        [ 5.00000000e-01, -1.56125113e-17, -5.00000000e-01,
         -6.09271796e-01],
        [ 5.00000000e-01,  1.50920942e-16, -5.00000000e-01,
          7.83349452e-01],
        [ 5.00000000e-01, -7.07106781e-01,  5.00000000e-01,
         -8.70388280e-02]]))

In [25]:
a=np.array([[2,4,0,4,1],[2,4,1,1,0],[1,1,1,2,2],[0,1,3,2,4],[2,2,2,0,2]])
linalg.inv(a)

array([[-0.6 ,  0.4 ,  1.6 , -0.6 , -0.1 ],
       [ 0.9 , -0.6 , -1.9 ,  0.4 ,  0.65],
       [-1.7 ,  1.8 ,  2.7 , -0.2 , -1.45],
       [-0.7 ,  0.8 ,  1.7 , -0.2 , -0.95],
       [ 1.4 , -1.6 , -2.4 ,  0.4 ,  1.4 ]])

In [27]:
np.trace(linalg.inv(a))

2.700000000000001